#!/usr/bin/env node
/**
 * build.js — regenerates the SEO blocks in index.html from games.json.
 *
 * games.json is the single source of truth. Run this after editing it:
 *     node build.js
 *
 * It rewrites two marked regions in index.html:
 *   - the crawlable <nav class="sr-only"> list of all games
 *   - the schema.org ItemList JSON-LD
 * Everything between the BEGIN/END markers is replaced; the markers stay.
 */
const fs = require("fs");
const path = require("path");

const root = __dirname;
const data = JSON.parse(fs.readFileSync(path.join(root, "games.json"), "utf8"));
const games = data.games || [];
const cats = data.categories || [];

const labelOf = (id) => (cats.find((c) => c.id === id) || {}).label || id;

// Order games by category order, then by their order within games.json.
const order = new Map(cats.map((c, i) => [c.id, i]));
const sorted = [...games].sort(
  (a, b) => (order.get(a.category) ?? 99) - (order.get(b.category) ?? 99)
);

// --- crawlable nav ---
const navItems = sorted
  .map(
    (g) =>
      `      <li><a href="${g.url}">${g.title} — ${labelOf(
        g.category
      ).toLowerCase()} game for kids</a></li>`
  )
  .join("\n");

// --- JSON-LD ItemList ---
const jsonld = {
  "@context": "https://schema.org",
  "@type": "ItemList",
  name: "Little Players Games",
  itemListElement: sorted.map((g, i) => ({
    "@type": "ListItem",
    position: i + 1,
    url: g.url,
    name: g.title,
  })),
};
const jsonldBlock =
  '  <script type="application/ld+json">\n  ' +
  JSON.stringify(jsonld, null, 2).replace(/\n/g, "\n  ") +
  "\n  </script>";

function replaceRegion(src, name, body) {
  const begin = `<!-- ${name}:BEGIN (auto-generated by build.js — do not edit) -->`;
  const end = `<!-- ${name}:END -->`;
  const re = new RegExp(
    begin.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") +
      "[\\s\\S]*?" +
      end.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
  );
  if (!re.test(src)) {
    throw new Error(`Markers for ${name} not found in index.html`);
  }
  return src.replace(re, `${begin}\n${body}\n  ${end}`);
}

const indexPath = path.join(root, "index.html");
let html = fs.readFileSync(indexPath, "utf8");
html = replaceRegion(html, "GAMES_NAV", navItems);
html = replaceRegion(html, "GAMES_JSONLD", jsonldBlock);
fs.writeFileSync(indexPath, html);

// --- sitemap.xml ---
const sitemap =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  '  <url><loc>https://littleplayers.github.io/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url>\n' +
  sorted
    .map(
      (g) =>
        `  <url><loc>${g.url}</loc><changefreq>monthly</changefreq><priority>0.8</priority></url>`
    )
    .join("\n") +
  "\n</urlset>\n";
fs.writeFileSync(path.join(root, "sitemap.xml"), sitemap);

console.log(
  `build.js: wrote ${games.length} games across ${cats.length} categories into index.html + sitemap.xml`
);
